### ISSUE TITLE
bug: can't install apps (worked once, not twice)

### ISSUE THREAD

**Issue by artybdrlt** [ketsapiwiq/ansible-yunohost-modules#1]
I hope I'm not too direct, too vague, this is the very first time I open an issue on someone else's project ;)

I've been trying to play with your ynh_app module.
So far, I managed to install an app once but can't make it work twice (quite weird I know^^):

```
- name: test module to install 20euros app (WORKING ONCE BUT NOT TWICE)
  ynh_app:
    name: "20euros"
    domain: "poclydra.fr"
    settings:
        path: '/20euros'
    label: 'Money'
    state: present
```
Basically I magically installed the app using the module, I double-checked and confirmed that it was installed and functional, I removed it using ynh cli and then I re-ran the playbook... Ansible can't install the app.

Here is the error message: 
`"module_stdout": "Traceback (most recent call last):\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636558074.5878353-33834-34674643789718/AnsiballZ_ynh_app.py\", line 100, in <module>\r\n    _ansiballz_main()\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636558074.5878353-33834-34674643789718/AnsiballZ_ynh_app.py\", line 92, in _ansiballz_main\r\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\r\n  File \"/home/arthur/.ansible/tmp/ansible-tmp-1636558074.5878353-33834-34674643789718/AnsiballZ_ynh_app.py\", line 41, in invoke_module\r\n    run_name='__main__', alter_sys=True)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 205, in run_module\r\n    return _run_module_code(code, init_globals, run_name, mod_spec)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 96, in _run_module_code\r\n    mod_name, mod_spec, pkg_name, script_name)\r\n  File \"/usr/lib/python3.7/runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"/tmp/ansible_ynh_app_payload_7vfy3s5z/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 602, in <module>\r\n  File \"/tmp/ansible_ynh_app_payload_7vfy3s5z/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 598, in main\r\n  File \"/tmp/ansible_ynh_app_payload_7vfy3s5z/ansible_ynh_app_payload.zip/ansible/modules/ynh_app.py\", line 392, in run_module\r\nTypeError: append() takes exactly one argument (2 given)\r\n",`

Environment: 
Running the playbook / Ansible module on a Debian 10 VM used for Yunohost Ansible role testing, no problems to install Yunohost or its apps whatsoever.

**Comment by ketsapiwiq** [comment]
Thanks for your 2 feedbacks, we're really gonna need serious unit testing + integration testing!!!
I'll check this soon and let you know!

**Comment by ketsapiwiq** [comment]
It should be way better now!

**Comment by artybdrlt** [comment]
Hello,
I have just tried with your newest update and it's much better indeed!
I can install apps flawlessly at once or with a loop. 
Thank you for your great work ;)
